### ISSUE TITLE
Supported/unsupported coins for swap: brc20-db20

### ISSUE THREAD

**Issue by teebszet** [alexgo-io/alex-sdk#2]
Have an issue to do with which coins we allow swaps from.

we are currently filtering coins list to swap like this:
```
const acceptableCoinList =
      coinsList?.filter((c) => alexSDK.getCurrencyFrom(c.principal) != null) ?? [];
```

in the case of brc20-db20, this passes:
```
alexSDK.getCurrencyFrom("SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.brc20-db20")
// brc20-db20
```

but if you try to run getFee or getRoute using "brc20-db20", you will get a ClarityError thrown:
```
decoders.js:74 Uncaught (in promise) Error: ClarityError: 2001
    at defaultErrorDecoder (decoders.js:74:1)
    at Object.decode (decoders.js:84:1)
    at _callee2$ (alex-sdk.esm.js:4018:1)
    at tryCatch (alex-sdk.esm.js:65:1)
    at Generator.<anonymous> (alex-sdk.esm.js:146:1)
    at Generator.next (alex-sdk.esm.js:90:1)
    at asyncGeneratorStep (alex-sdk.esm.js:327:1)
    at _next (alex-sdk.esm.js:346:1)
```

**Comment by fiftyeightandeight** [comment]
@zhigang1992 @bolasblack this feature (of getting the list of supported tokens) was requested by others too. Think something we want to implement either as an API endpoint or as part of SDK?
Also, we don't have AMM on `brc20-db20`, so this shouldn't be included (though we will add one pretty soon).
